export { default as Home } from "./Home";
export { default as Speakers } from "./Speakers";
export { default as Earphones } from "./Earphones";
export { default as Headphones } from "./Headphones";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as SingleProduct } from "./SingleProduct";
export { default as Checkout } from "./Checkout";
export { default as Error } from "./Error";
